### PR TITLE
Update CoverComponent with new styles

### LINKED ISSUE #167: Redesign Cover button and animation
Its time to upgrade folks.

### PR DESCRIPTION
**Pull request by knikel**
### Changes
* Clickable `.svg` logo, links to a photo in the viewer through `target="_blank"`
* Explore button with matching transition to what’s on mapillary.com
* Background hover transition matching _Featured photos_ section on mapillary.com

### Notes
* Approved by @angelday
* Closes #167

### CODE REVIEW

**Comment by gyllen** [comment]
@oscarlorentzon Anyway we can get this in, in the next release?

**Comment by oscarlorentzon** [comment]
Yes, this will be in the next release.

**Comment by gyllen** [comment]
@oscarlorentzon 👍

**Comment by knikel** [comment]
👏 Thanks @nickplesha and @oscarlorentzon for completing it!

**Pull request merged**
