### PR TITLE
Add 'lookAt' API

### PR DESCRIPTION
**Pull request by Neurostep**
Hi,

This PR includes new API function – `lookAt` see #156 for more details

It is not absolutely clear how to implement this method regarding [the API](https://a.mapillary.com/#search-search). Exploring the API and the codebase I believe that there are two ways to do so:
1. Just do the same as in `moveCloseTo` but without  touching `navigator`;
2. Try to use `/search/im/` [endpoint](https://a.mapillary.com/#get-searchim) to get exact image by coordinates.

I guess that my assumptions are could be wrong and maybe existed the more accurate way to implement `lookAt` method. If so, I hope we can do it by reviewing this PR :)

Please, review.

### CODE REVIEW

**Comment by gyllen** [comment]
We are currently implementing a new lookAt API I think we should hold of with this PR until that is done.

**Comment by Neurostep** [comment]
@gyllen Sounds reasonable. If I understood correctly, there will be new endpoint (on server-side), like `/im/lookat?lon=<lon>&lat=<lat>`, correct? If so, it will help a lot.
So, let's postpone this PR for now. Please, ping me when it is done, I will finish it then.

**Comment by gyllen** [comment]
@Neurostep Awesome thanks. We are actually looking into v3 of the API right now and I think something like 

`/v3/images?look_at[lon]=-82.7057&look_at[lat]=41.5953&look_at[radius]=100`

Will make more sense for the API. There should only be one API to get images. Not a specific search one (thats my thoughts right now).

**Comment by oscarlorentzon** [comment]
I will close this PR for the following reasons:

1. APIv2 which is used in the PR commits has been removed completely from the library.
2. The `Navigator` has been refactored during the implementation of the new `Graph`.
3. It will be easier to start from scratch than building upon the work done in the commits in this PR (which were valid for APIv2) once APIv3 is released.

Thanks a lot for putting in the effort of making this PR @Neurostep. To bad the timing was unfortunate. 

@gyllen can provide more info about APIv3.

**Comment by Neurostep** [comment]
Thanks for letting me know. Looking forward to dive into new APIv3 once it is released

**Pull request closed without merging**
